config/routes.rb
Rails.application.routes.draw do
  namespace :manager do
    resources 'customers', only: [:index, :new, :create]
  end

  resources 'balances', only: :index do
  end
  post 'balances/search' => 'balances#search'
  resources 'users', only: :index

  resources :manager_visits, only: [:index, :create]

  get 'investments_portfolio' => 'investments_portfolio#index'
  post 'investments_portfolio/purchase' => 'investments_portfolio#purchase'
  post 'investments_portfolio/sale' => 'investments_portfolio#sale'

  get 'transactions/new/:kind' => 'transactions#new', as: :transaction_new
  post 'transactions' => 'transactions#create'

  devise_for :users
  get '/' => 'home#index'

end

app/controllers/investments_portfolio_controller.rb
class InvestmentsPortfolioController < ApplicationController
  before_filter :load_investments, only: :index
  after_filter :load_investments, only: [:sale, :purchase]
  def index
  end

  def purchase
    InvestimentsManager.purchase(params[:investments_portfolio].values)
    load_investments
  end

  def sale
    InvestimentsManager.sale(investments_portfolio_params, current_user)
    load_investments
  end

  private

  def investments_portfolio_params
    params.require(:investment_portfolio).permit(:id, :sale_price, :status, :sale_quantity)
  end

  def load_investments
    @investments = InvestimentsManager.quotations
    @investment_portfolios = InvestimentsManager.user_investments(current_user)
  end
end

app/helpers/investments_portfolio_helper.rb
module InvestmentsPortfolioHelper
end

app/views/investments_portfolio/_purchase_actions.html.erb
  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading"><h3>Comprar ações</h3></div>
      <div class="panel-body">
        <%= form_tag investments_portfolio_purchase_path, remote: true do |f| %>
          <table class="table table-condensed table-striped">
            <% @investments.each_with_index do |investment, i| %>
              <tr>
                <td><%= investment['symbol'] %></td>
                <td><%= investment['LastTradePriceOnly'] %></td>
                <td>
                  <%= hidden_field_tag "investments_portfolio[#{i}]user_id", current_user.id %>
                  <%= hidden_field_tag "investments_portfolio[#{i}]action", investment["symbol"] %>
                  <%= hidden_field_tag "investments_portfolio[#{i}]status", :purchased %>
                  <%= hidden_field_tag "investments_portfolio[#{i}]purchase_price", investment["LastTradePriceOnly"] %>
                  <%= number_field_tag "investments_portfolio[#{i}]quantity" %>
                </td>
              </tr>
            <% end %>
          </table>
          <%= submit_tag "Comprar", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/investments_portfolio/_sale_actions.html.erb
  <div class="col-md-8">
    <div class="panel panel-primary">
      <div class="panel-heading"><h3>Vender Ações</h3></div>
      <div class="panel-body">
        <table class="table table-condensed table-striped">
          <thead>
            <tr>
              <th>Ação</th>
              <th>Status</th>
              <th>$ de Compra</th>
              <th>Qtde Comprada</th>
              <th>$ de Venda</th>
              <th>Qtde Venda</th>
              <th>#</th>
            </tr>
          </thead>
          <tbody>
            <% @investment_portfolios.each_with_index do |investment, i| %>
              <tr>
                <td><%= investment.action %></td>
                <td> <%= investment.status %> </td>
                <td> <%= investment.purchase_price %> </td>
                <td> <%= investment.quantity%> </td>
                <td> <%= investment.sale_price %> </td>
                <td>
                  <%= number_field_tag "sale[#{i}]quantity" %>
                </td>
                <td>
                  <% if investment.purchased?#[:status].eql?('purchased') %>
                    <%= link_to "Vender", "#", data: { url: investments_portfolio_sale_path,
                                                  id: investment.id,
                                                  status: :sold,
                                                  sale_price: investment.sale_price, index: i},
                                                  remote: true, class: "btn btn-sm btn-primary sale" %>
                  <% else %>
                    <span class="">vendido</span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

app/views/investments_portfolio/index.html.erb
<div class="row">
  <div id="purchase_actions">
    <%= render "purchase_actions" %>
  </div>
  <div id="sale_actions">
    <%= render "sale_actions"  %>
  </div>
</div>

app/views/investments_portfolio/purchase.coffee.erb
$("#sale_actions").html(<%=j render('sale_actions').html_safe %>)
$("#purchase_actions").html(<%=j render('purchase_actions').html_safe %>)

app/views/investments_portfolio/sale.coffee.erb
$("#sale_actions").html(<%=j render('sale_actions').html_safe %>)
$("#purchase_actions").html(<%=j render('purchase_actions').html_safe %>)