config/routes.rb
Rails.application.routes.draw do
  namespace :manager do
    resources 'customers', only: [:index, :new, :create]
  end

  resources 'balances', only: :index do
  end
  post 'balances/search' => 'balances#search'
  resources 'users', only: :index

  resources :manager_visits, only: [:index, :create]

  get 'investments_portfolio' => 'investments_portfolio#index'
  post 'investments_portfolio/purchase' => 'investments_portfolio#purchase'
  post 'investments_portfolio/sale' => 'investments_portfolio#sale'

  get 'transactions/new/:kind' => 'transactions#new', as: :transaction_new
  post 'transactions' => 'transactions#create'

  devise_for :users
  get '/' => 'home#index'

end

app/models/balance.rb
# == Schema Information
#
# Table name: balances
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  amount         :float(24)        default("0")
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  last_operation :datetime
#

class Balance < ActiveRecord::Base
  belongs_to :user
  has_many :transactions

  def add(value)
    self.amount += value
    save!
  end

  def subtract(value)
    raise "Você não tem saldo suficiente para esta transação" if value > self.amount && user.normal?
    self.amount -= value
    save
  end

  def amount
    if super < 0
      diff_in_minutes = ((Time.now - self.last_operation) / 60).round
      result = (super + super * diff_in_minutes * 0.1 / 100).round
      return result
    end
    read_attribute(:amount)
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  def index
    @extract = BalanceManager.extract(current_user)
  end

  def search
    @extract = BalanceManager.extract(current_user, params[:start_at].to_datetime, params[:end_at].to_datetime)
  end
end

app/helpers/balances_helper.rb
module BalancesHelper
  def item_amount_extract(amount, type)
    currency = number_to_currency(amount, unit: "R$ ", separator: ",", delimiter: ".")
    return currency if type.eql?('C')
    "(-#{currency})"
  end
end

app/views/balances/_result.html.erb
<table class="table table-condensed table-striped">
  <thead>
    <tr>
      <th>Valor</th>
      <th>Data</th>
      <th>Tipo</th>
      <th>Descrição</th>
    </tr>
  </thead>
  <tbody>
    <% extract.each_with_index do |extract| %>
      <tr>
        <td>
          <%= item_amount_extract(extract.amount, extract.type) %>
        </td>
        <td>
          <%= extract.done_at.utc.strftime("%d/%m/%Y %H:%M:%S") %>
        </td>
        <td>
          <%= extract.type%>
        </td>
        <td>
          <%= extract.description%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/balances/index.html.erb
<div class="col-md-10">
  <div class="panel panel-default">
    <div class="panel-heading"><h3>Extrato</h3></div>
    <div class="panel-body">
      <%= form_tag balances_search_path, remote: true do %>

        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= text_field_tag :start_at, nil, class: 'form-control datepicker', placeholder: 'Data Inicial' %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="form-group">
              <%= text_field_tag :end_at, nil, class: 'form-control datepicker', placeholder: 'Data Final'%>
            </div>
          </div>
          <div class="col-md-4">
            <%= submit_tag 'Pesquisar', class: "btn btn-primary" %>
          </div>
        </div>
        <div id="result">

        </div>
      <% end %>
    </div>
    <div class="panel-footer">
      Saldo: <%= current_user.balance.amount %>
    </div>
  </div>
</div>

app/views/balances/search.js.erb
$('#result').html('<%= j render('result', extract: @extract)  %>')