config/routes.rb
Rails.application.routes.draw do
  namespace :manager do
    resources 'customers', only: [:index, :new, :create]
  end

  resources 'balances', only: :index do
  end
  post 'balances/search' => 'balances#search'
  resources 'users', only: :index

  resources :manager_visits, only: [:index, :create]

  get 'investments_portfolio' => 'investments_portfolio#index'
  post 'investments_portfolio/purchase' => 'investments_portfolio#purchase'
  post 'investments_portfolio/sale' => 'investments_portfolio#sale'

  get 'transactions/new/:kind' => 'transactions#new', as: :transaction_new
  post 'transactions' => 'transactions#create'

  devise_for :users
  get '/' => 'home#index'

end

app/controllers/manager/customers_controller.rb
class Manager::CustomersController < ApplicationController
  def index
    @customers = current_user.customers
  end

  def new
    @customer = current_user.customers.build
  end

  def create
    @customer = current_user.customers.build(customer_params)
    @customer.save!
  end

  def customer_params
    params.require(:user).permit(:name, :account, :password, :kind)
  end
end

app/helpers/manager/customers_helper.rb
module Manager::CustomersHelper
end

app/views/manager/customers/create.html.erb
<h1>Manager::Customers#create</h1>
<p>Find me in app/views/manager/customers/create.html.erb</p>

app/views/manager/customers/index.html.erb
<div class="col-md-8">
  <div class="panel panel-default">
    <div class="panel-heading"><h3>Clientes</h3></div>
    <div class="panel-body">
      <table class="table table-condensed table-striped">
        <thead>
          <tr>
            <th>Nome</th>
            <th>Conta</th>
          </tr>
        </thead>
        <tbody>
        <% @customers.each_with_index do |customer| %>
          <tr>
            <td>
              <%= customer.name %>
            </td>
            <td>
              <%= customer.account %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<div class="actions col-md-8">
  <%= link_to "Cadastrar Cliente", new_manager_customer_path, class: "btn btn-primary" %>
</div>

app/views/manager/customers/new.html.erb
  <div class="col-md-6 col-md-offset-3">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Cadastrar Cliente</h3>
      </div>
      <div class="panel-body">
        <%= form_for @customer, url: manager_customers_url do |f| %>
          <%= f.hidden_field :manager_id, value: f.object.id %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-control", placeholder: "Nome" %>
          </div>
          <div class="form-group">
            <%= f.text_field :account, class: "form-control", placeholder: "Conta" %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, class: "form-control", placeholder: "Senha" %>
          </div>
          <div class="form-group">
            <%= f.select :kind, [['Selecione', nil],['Normal', :normal], ['VIP', :VIP]], {}, class: "form-control", placeholder: "Senha" %>
          </div>
          <div class="actions">
            <%= f.submit "Cadastrar", class: "btn btn-lg btn-success btn-block" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>