config/routes.rb
Rails.application.routes.draw do
  namespace :manager do
    resources 'customers', only: [:index, :new, :create]
  end

  resources 'balances', only: :index do
  end
  post 'balances/search' => 'balances#search'
  resources 'users', only: :index

  resources :manager_visits, only: [:index, :create]

  get 'investments_portfolio' => 'investments_portfolio#index'
  post 'investments_portfolio/purchase' => 'investments_portfolio#purchase'
  post 'investments_portfolio/sale' => 'investments_portfolio#sale'

  get 'transactions/new/:kind' => 'transactions#new', as: :transaction_new
  post 'transactions' => 'transactions#create'

  devise_for :users
  get '/' => 'home#index'

end

app/models/balance.rb
# == Schema Information
#
# Table name: balances
#
#  id             :integer          not null, primary key
#  user_id        :integer
#  amount         :float(24)        default("0")
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  last_operation :datetime
#

class Balance < ActiveRecord::Base
  belongs_to :user
  has_many :transactions

  def add(value)
    self.amount += value
    save!
  end

  def subtract(value)
    raise "Você não tem saldo suficiente para esta transação" if value > self.amount && user.normal?
    self.amount -= value
    save
  end

  def amount
    if super < 0
      diff_in_minutes = ((Time.now - self.last_operation) / 60).round
      result = (super + super * diff_in_minutes * 0.1 / 100).round
      return result
    end
    read_attribute(:amount)
  end
end

app/models/investment_portfolio.rb
# == Schema Information
#
# Table name: investment_portfolios
#
#  id             :integer          not null, primary key
#  action         :string(255)
#  status         :integer
#  purchase_price :float(24)
#  sale_price     :float(24)
#  user_id        :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  quantity       :integer
#  sale_quantity  :integer
#

class InvestmentPortfolio < ActiveRecord::Base
  belongs_to :user

  ACTIONS = %w(PETR4.SA VALE5.SA BVMF3.SA BRML3.SA ALSC3.SA MULT3.SA BBAS3.SA ITSA6.SA)

  validates_inclusion_of :action, :in => ACTIONS

  enum status: [:purchased, :sold]
end

app/models/manager_visit.rb
# == Schema Information
#
# Table name: manager_visits
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  manager_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  amount     :float(24)
#

class ManagerVisit < ActiveRecord::Base
  belongs_to :user
  belongs_to :manager, class_name: "User", foreign_key: 'manager_id'
end

app/models/transaction.rb
# == Schema Information
#
# Table name: transactions
#
#  id             :integer          not null, primary key
#  kind           :string(255)
#  amount         :float(24)        default("0")
#  balance_id     :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_target_id :integer
#  user_source_id :integer
#

class Transaction < ActiveRecord::Base
  belongs_to :balance
  belongs_to :user_target, class_name: "User", foreign_key: 'user_target_id'
  belongs_to :user_source, class_name: "User", foreign_key: 'user_source_id'
  [:transfer, :withdraw, :deposit, :tax]
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  account                :string(255)
#  password               :string(255)
#  kind                   :integer
#  manager                :boolean          default("0")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  manager_id             :integer
#

class User < ActiveRecord::Base
  has_one :balance
  has_many :transactions, class_name: 'Transaction', foreign_key: 'user_source_id'
  has_many :customers, class_name: 'User', foreign_key: 'manager_id'
  has_many :transactions_for_me, class_name: 'Transaction', foreign_key: 'user_target_id'
  has_many :investment_portfolios
  has_many :manager_visits
  belongs_to :my_manager, class_name: 'User', foreign_key: 'manager_id'

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, authentication_keys: [:account]

  validates_presence_of :name
  validates_presence_of :account
  validates_presence_of :password


  enum kind: [:normal, :VIP, :manager]

  after_create :create_balance

  def email_required?
    false
  end

  def email_changed?
    false
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  layout :layout_by_resource

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def layout_by_resource
    if devise_controller?
      "login"
    else
      "application"
    end
  end
end

app/controllers/balances_controller.rb
class BalancesController < ApplicationController
  def index
    @extract = BalanceManager.extract(current_user)
  end

  def search
    @extract = BalanceManager.extract(current_user, params[:start_at].to_datetime, params[:end_at].to_datetime)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    return if current_user.manager?

    @balance = current_user.balance.amount
    @investiments = InvestimentsManager.quotations
  end
end

app/controllers/investments_portfolio_controller.rb
class InvestmentsPortfolioController < ApplicationController
  before_filter :load_investments, only: :index
  after_filter :load_investments, only: [:sale, :purchase]
  def index
  end

  def purchase
    InvestimentsManager.purchase(params[:investments_portfolio].values)
    load_investments
  end

  def sale
    InvestimentsManager.sale(investments_portfolio_params, current_user)
    load_investments
  end

  private

  def investments_portfolio_params
    params.require(:investment_portfolio).permit(:id, :sale_price, :status, :sale_quantity)
  end

  def load_investments
    @investments = InvestimentsManager.quotations
    @investment_portfolios = InvestimentsManager.user_investments(current_user)
  end
end

app/controllers/manager_visits_controller.rb
class ManagerVisitsController < ApplicationController
  def index
    @visits = ManagerVisit.all
  end

  def create
    current_user.manager_visits.create(manager: User.where(manager: true).first, amount: 250.0)
    balance = current_user.balance
    balance.subtract(250.0)

    redirect_to :manager_visits
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def new
    @transaction = Transaction.new(kind: params[:kind])
  end

  def create
    @transaction = Transaction.new(transaction_params)
    result = transaction_manager.do_transaction(@transaction, params[:user_target])
    if result.success?
      flash[:notice] = result.message
    else
      flash[:danger] = result.message
    end
    redirect_to transaction_new_url(transaction_params[:kind])
  end

  private

  def transaction_manager
    @transaction_manager ||= TransactionManager.new(current_user)
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :kind, :user_source_id, :balance_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/balances_helper.rb
module BalancesHelper
  def item_amount_extract(amount, type)
    currency = number_to_currency(amount, unit: "R$ ", separator: ",", delimiter: ".")
    return currency if type.eql?('C')
    "(-#{currency})"
  end
end

app/helpers/home_helper.rb
module HomeHelper
  def balance
    number_to_currency(@balance, unit: "R$", separator: ",", delimiter: ".")
  end
end

app/helpers/investments_portfolio_helper.rb
module InvestmentsPortfolioHelper
end

app/helpers/manager/customers_helper.rb
module Manager::CustomersHelper
end

app/helpers/manager_visits_helper.rb
module ManagerVisitsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NilBank</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <!-- Static navbar -->
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Página Inicial</a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <% if current_user.manager? %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Clientes<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>

                      <%= link_to "Listagem", manager_customers_path %>
                    </li>
                    <li>
                      <%= link_to "Cadastrar Cliente", new_manager_customer_path %>
                    </li>
                  </ul>
                </li>
              <% else %>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ver<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li><a href="/">Saldo</a></li>
                    <li>
                      <%= link_to "Extrato", balances_path %>
                    </li>
                  </ul>
                </li>
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Transações<span class="caret"></span></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to "Saque", transaction_new_path(:withdraw) %>
                    </li>
                    <li>
                      <%= link_to "Depósito", transaction_new_path(:deposit) %>
                    </li>
                    <li>
                      <%= link_to "Transferência", transaction_new_path(:transfer) %>
                    </li>
                  </ul>
                </li>
                <li>
                  <%= link_to "Investimentos", investments_portfolio_path %>
                </li>
                <li>
                  <%= link_to "Visitas do Gerente", manager_visits_path%>
                </li>
              <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <%= link_to('Trocar Usuário', destroy_user_session_path, :method => :delete, class: "btn btn-danger") %>
              </li>
            </ul>
          </div><!-- /.navbar-collapse -->
        </div><!-- /.container-fluid -->
      </nav>

      <div>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NilBank</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>